DROP TABLE IF EXISTS [groups];
CREATE TABLE [groups] (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name STRING UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
 id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  fullname name STRING,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  
);
DROP TABLE IF EXISTS students;
CREATE TABLE students (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  fullname name STRING,
  group_id REFERENCES [groups] (id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );
DROP TABLE IF EXISTS items;
CREATE TABLE  items (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name STRING,
  teachers_id REFERENCES [teachers] (id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  
);
DROP TABLE IF EXISTS facultet;
CREATE TABLE facultet (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name STRING,
  group_id REFERENCES [groups] (id),
  student_id REFERENCES [students] (id),
  teacher_id REFERENCES [teachers] (id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS grades;
CREATE TABLE grades (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  grade INTEGER,
  items_id REFERENCES items (id),
  student_id REFERENCES students (id),
  date_of DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);